# Generated by Django 5.2.4 on 2026-01-21 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Terjual')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Satuan (Rp)')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Total Penjualan')),
                ('buyer_name', models.CharField(default='Umum', max_length=255, verbose_name='Nama Pembeli')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Transaksi')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='sales/', verbose_name='Bukti')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product', verbose_name='Pilih Produk (Stok Tersedia)')),
            ],
        ),
    ]
