# Generated by Django 5.2.4 on 2026-04-21 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_stockadjustment_options_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(default='General', max_length=255, verbose_name='Buyer Name'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Unit Price (IDR)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product', verbose_name='Select Product (Available Stock)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='sales/', verbose_name='Proof'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Sold'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Total Sales Amount'),
        ),
    ]
