# Generated by Django 5.2.4 on 2026-01-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Aset')),
                ('type', models.CharField(choices=[('lahan', 'Lahan'), ('alat', 'Alat'), ('bangunan', 'Bangunan'), ('ternak', 'Ternak')], max_length=100, verbose_name='Tipe Aset')),
                ('location', models.CharField(max_length=100, verbose_name='Lokasi')),
                ('size', models.FloatField(blank=True, null=True, verbose_name='Ukuran (m²)')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Nilai Aset')),
                ('acquisition_date', models.DateField(verbose_name='Tanggal Akuisisi')),
                ('ownership_status', models.CharField(choices=[('full_ownership', 'Full Ownership'), ('partial_ownership', 'Partial Ownership'), ('investor_owned', 'Investor Owned'), ('leashold', 'Leased'), ('under_construction', 'Under Construction'), ('personal_ownership', 'Personal Ownership')], max_length=50, verbose_name='Status Kepemilikan')),
                ('landowner', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pemilik Lahan')),
                ('landowner_share_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Bagi Hasil Pemilik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Foto/Dokumen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aset',
                'verbose_name_plural': 'Aset',
            },
        ),
    ]
