# Generated by Django 5.2.4 on 2026-04-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquisition_date',
            field=models.DateField(verbose_name='Acquisition Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Photo/Document'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='landowner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landowner Name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='landowner_share_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Landowner Share %'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Asset Name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ownership_status',
            field=models.CharField(choices=[('full_ownership', 'Full Ownership'), ('partial_ownership', 'Partial Ownership'), ('investor_owned', 'Investor Owned'), ('leashold', 'Leased'), ('under_construction', 'Under Construction'), ('personal_ownership', 'Personal Ownership')], max_length=50, verbose_name='Ownership Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Size (m2)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('lahan', 'Land'), ('alat', 'Equipment'), ('bangunan', 'Building'), ('ternak', 'Livestock')], max_length=100, verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Asset Value'),
        ),
    ]
