# Generated by Django 5.2.4 on 2026-01-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_system_shares', models.PositiveIntegerField(default=15000, verbose_name='Total Lembar Saham')),
                ('share_price', models.DecimalField(decimal_places=2, default=100000, max_digits=15, verbose_name='Harga Per Lembar')),
            ],
            options={
                'verbose_name': 'Dashboard & Konfigurasi',
                'verbose_name_plural': 'Dashboard & Konfigurasi',
            },
        ),
    ]
