# Generated by Django 5.2.4 on 2026-04-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'Dashboard & Configuration', 'verbose_name_plural': 'Dashboard & Configuration'},
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='share_price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=15, verbose_name='Price Per Share'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='total_system_shares',
            field=models.PositiveIntegerField(default=15000, verbose_name='Total Share Units'),
        ),
    ]
