# Generated by Django 5.2.4 on 2026-04-21 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profitdistribution',
            options={'ordering': ['-date'], 'verbose_name': 'Profit Distribution', 'verbose_name_plural': 'Profit Distribution History'},
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Distribution Date'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='total_distributed',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Distributed Amount'),
        ),
        migrations.AlterField(
            model_name='profitdistributionitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Received Amount'),
        ),
    ]
