# Generated by Django 5.2.4 on 2026-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shares', models.PositiveIntegerField(default=10000, help_text='Total lembar saham yang diterbitkan perusahaan')),
                ('share_price', models.DecimalField(decimal_places=2, default=1000000, help_text='Harga per lembar saham (Estimasi)', max_digits=15)),
                ('max_share_per_investor', models.PositiveIntegerField(default=50, help_text='Maksimal persentase kepemilikan per investor (0-100)')),
                ('company_name', models.CharField(default='Integrated Estate', max_length=100)),
                ('support_email', models.EmailField(default='admin@lahanpintar.com', max_length=254)),
                ('enable_notifications', models.BooleanField(default=True)),
            ],
        ),
    ]
