# Generated by Django 5.2.4 on 2026-01-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='company_name',
            field=models.CharField(default='Integrated Estate', max_length=100),
        ),
    ]
