# Generated by Django 5.2.4 on 2026-04-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesetting_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='max_share_per_investor',
            field=models.PositiveIntegerField(default=50, help_text='Maximum ownership percentage per investor (0-100)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='share_price',
            field=models.DecimalField(decimal_places=2, default=1000000, help_text='Estimated price per share', max_digits=15),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='total_shares',
            field=models.PositiveIntegerField(default=10000, help_text='Total number of shares issued by the company'),
        ),
    ]
