# Generated by Django 5.2.4 on 2026-01-21 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('OPERATIONAL', 'Operational Cost'), ('SALARY', 'Salary/Wages'), ('ASSET_PURCHASE', 'Asset Purchase'), ('TAX', 'Tax & Legal'), ('OTHERS', 'Others')], default='OPERATIONAL', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('recipient', models.CharField(blank=True, help_text='Who received the money?', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
