# Generated by Django 5.2.4 on 2026-01-21 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, verbose_name='Nama Investor/Donatur')),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontak (HP/Email)')),
                ('source_type', models.CharField(choices=[('investor', 'Investor'), ('donation', 'Donasi')], default='investor', max_length=20, verbose_name='Tipe Dana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah Dana (Rp)')),
                ('shares', models.PositiveIntegerField(blank=True, help_text='Wajib diisi jika Investor', null=True, verbose_name='Lembar Saham')),
                ('date_received', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Diterima')),
                ('payment_method', models.CharField(choices=[('transfer', 'Transfer Bank'), ('cash', 'Tunai'), ('qris', 'QRIS/E-Wallet')], default='transfer', max_length=20, verbose_name='Metode Pembayaran')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='funding/proofs/', verbose_name='Bukti Transfer')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pendanaan',
                'verbose_name_plural': 'Daftar Pendanaan',
                'ordering': ['-date_received'],
            },
        ),
    ]
