# Generated by Django 5.2.4 on 2026-04-21 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ['-date_received'], 'verbose_name': 'Funding', 'verbose_name_plural': 'Funding Records'},
        ),
        migrations.AlterField(
            model_name='funding',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Funding Amount (IDR)'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact (Phone/Email)'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Bank Transfer'), ('cash', 'Cash'), ('qris', 'QRIS/E-Wallet')], default='transfer', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='funding/proofs/', verbose_name='Transfer Proof'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='shares',
            field=models.PositiveIntegerField(blank=True, help_text='Required when source type is Investor', null=True, verbose_name='Share Units'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='source_name',
            field=models.CharField(max_length=255, verbose_name='Investor/Donor Name'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='source_type',
            field=models.CharField(choices=[('investor', 'Investor'), ('donation', 'Donation')], default='investor', max_length=20, verbose_name='Funding Type'),
        ),
    ]
