# Generated by Django 5.2.4 on 2026-01-21 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('stok', 'Masuk Stok'), ('terjual', 'Langsung Terjual')], default='stok', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='asset.asset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_history', to='production.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('addition', 'Penambahan Stok'), ('reduction', 'Pengurangan Stok')], max_length=20, verbose_name='Tipe Adjustment')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Penyesuaian')),
                ('reason', models.CharField(choices=[('damaged', 'Barang Rusak'), ('expired', 'Kadaluarsa'), ('pest', 'Dimakan Hama/Tikus'), ('theft', 'Kehilangan/Pencurian'), ('recount', 'Koreksi Perhitungan'), ('found', 'Stok Ditemukan'), ('other', 'Lainnya')], max_length=50, verbose_name='Alasan')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('date', models.DateField(verbose_name='Tanggal Penyesuaian')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='stock_adjustments/', verbose_name='Bukti Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='production.product')),
            ],
            options={
                'verbose_name': 'Penyesuaian Stok',
                'verbose_name_plural': 'Riwayat Penyesuaian Stok',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
