# Generated by Django 5.2.4 on 2026-04-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Stock Adjustment', 'verbose_name_plural': 'Stock Adjustment History'},
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('stok', 'Inbound Stock'), ('terjual', 'Sold Immediately')], default='stok', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('addition', 'Stock Increase'), ('reduction', 'Stock Reduction')], max_length=20, verbose_name='Adjustment Type'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='date',
            field=models.DateField(verbose_name='Adjustment Date'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='stock_adjustments/', verbose_name='Photo Proof'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Adjustment Quantity'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Damaged Goods'), ('expired', 'Expired'), ('pest', 'Pest Damage'), ('theft', 'Loss/Theft'), ('recount', 'Recount Correction'), ('found', 'Recovered Stock'), ('other', 'Other')], max_length=50, verbose_name='Reason'),
        ),
    ]
